### ISSUE TITLE
Returncode 0 even when error

### ISSUE THREAD

**Issue by ChristianMichelsen** [metaDMG-dev/metaDMG-cpp#5]
Hi,

When running metaDMG-cpp on an unsorted alignment file, we correctly get:

`-> ERROR: We require files to be sorted by readname, will exit`

however, the returncode is 0. 

`checkIfSorted` correctly returns a non-0 integer, but this is not properly propagated.

**Comment by ChristianMichelsen** [comment]
I'll let you do it such that it is done properly.

**Comment by ANGSD** [comment]
done in most recent commit.

**Comment by ChristianMichelsen** [comment]
Hm, after updating metaDMG-cpp I still get the same error. I use the data that Mikkel described and run it like:

`./metaDMG-cpp lca -bam raw_data/mikkel_test/b8d9f2e0b2.sort.bam -outnames data/tmp/b8d9f2e0b2/b8d9f2e0b2 -names raw_data/mikkel_test/names.dmp -nodes raw_data/mikkel_test/nodes.dmp -acc2tax raw_data/mikkel_test/acc2taxid.map.gz -simscorelow 0.95 -simscorehigh 1.0    -minmapq 0 -howmany 35 -weighttype 1 -fix_ncbi 1 -tempfolder data/tmp/b8d9f2e0b2/`

which gives: 

```
	-> metaDMG version: 0.2-46-gddb3802-dirty (htslib: 1.15.1) build(Aug 17 2022 11:34:47)
#./metaDMG-cpp lca -bam raw_data/mikkel_test/b8d9f2e0b2.sort.bam -outnames data/tmp/b8d9f2e0b2/b8d9f2e0b2 -names raw_data/mikkel_test/names.dmp -nodes raw_data/mikkel_test/nodes.dmp -acc2tax raw_data/mikkel_test/acc2taxid.map.gz -simscorelow 0.95 -simscorehigh 1.0 -minmapq 0 -howmany 35 -weighttype 1 -fix_ncbi 1 -tempfolder data/tmp/b8d9f2e0b2/
	-> Will output lca results in file:		'data/tmp/b8d9f2e0b2/b8d9f2e0b2.lca.gz'
	-> [thread1] Will read header
	-> Will output lca distribution in file:		'data/tmp/b8d9f2e0b2/b8d9f2e0b2.stat'
	-> Will output lca weight in file:		'data/tmp/b8d9f2e0b2/b8d9f2e0b2.wlca'
	-> Will output log info (problems) in file:	'data/tmp/b8d9f2e0b2/b8d9f2e0b2.log'
	-> ERROR: We require files to be sorted by readname, will exit
```

but `echo $?` returns `0`

**Comment by ANGSD** [comment]
fixed

**Comment by ChristianMichelsen** [comment]
Works now. Thanks!
